// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUWQPEqk1Pwf5r1UMoxSKhJavAOJIpdjQ',
    appId: '1:438144428274:web:dc629e9cd249447f07486b',
    messagingSenderId: '438144428274',
    projectId: 'riverpod-chat-126ce',
    authDomain: 'riverpod-chat-126ce.firebaseapp.com',
    storageBucket: 'riverpod-chat-126ce.firebasestorage.app',
    measurementId: 'G-Z7703FMY04',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUwt57w9XiyqvXbidBWGNmzx1-r_iiAq8',
    appId: '1:438144428274:android:76bfddb426122ab107486b',
    messagingSenderId: '438144428274',
    projectId: 'riverpod-chat-126ce',
    storageBucket: 'riverpod-chat-126ce.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGDmy-O6jXbK0Je7gCYPSI2DVCAWyIDCI',
    appId: '1:438144428274:ios:fbc17bdaf32ce19907486b',
    messagingSenderId: '438144428274',
    projectId: 'riverpod-chat-126ce',
    storageBucket: 'riverpod-chat-126ce.firebasestorage.app',
    iosBundleId: 'com.example.riverpodChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGDmy-O6jXbK0Je7gCYPSI2DVCAWyIDCI',
    appId: '1:438144428274:ios:fbc17bdaf32ce19907486b',
    messagingSenderId: '438144428274',
    projectId: 'riverpod-chat-126ce',
    storageBucket: 'riverpod-chat-126ce.firebasestorage.app',
    iosBundleId: 'com.example.riverpodChat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBUWQPEqk1Pwf5r1UMoxSKhJavAOJIpdjQ',
    appId: '1:438144428274:web:f24558f9456da7ce07486b',
    messagingSenderId: '438144428274',
    projectId: 'riverpod-chat-126ce',
    authDomain: 'riverpod-chat-126ce.firebaseapp.com',
    storageBucket: 'riverpod-chat-126ce.firebasestorage.app',
    measurementId: 'G-R282028DE8',
  );
}
